### PR TITLE
CTOR default param injection 

### PR DESCRIPTION
**Pull request by MikeMitterer**
It's to bad: Chrome gives "Unsupported operation: Named arguments are not implemented."
However - it works at least in none Chrome environment.

### CODE REVIEW

**Comment by MikeMitterer** [comment]
At least optional param works

**Comment by MikeMitterer** [comment]
I've ported almost all my libs and applications to dice so pace will slow down in the next few days...

**Comment by MikeMitterer** [comment]
I move the example from `example` to `samples`. Works better. The recommend Dart way (example-folder) fails if you have more examples with different pubspec-configurations.  (other than the main pubspec)

**Comment by MikeMitterer** [comment]
Any news on this PR?

**Comment by ltackmann** [comment]
Hi i am on vacation, will be back in a det days

**Pull request merged**
