### PR TITLE
Support inherited properties when resolving injections. (Issue #28)

### PR DESCRIPTION
**Pull request by KOGI**
This resolves Issue #28

### CODE REVIEW

**Comment by jonkirkman** [comment]
@KOGI Do you think any tests should be added (or improved) in order to validate this?

**Comment by KOGI** [comment]
@Itackmann, when can we expect a release with this new functionality included? We could really use it on our project!

**Comment by ltackmann** [comment]
Hi

Its now released as version 1.8, I could use some contributors so if you
want I can add you to the pub spec so you can also upload new versions

**Comment by KOGI** [comment]
Thank you!

**Comment by MikeMitterer** [comment]
this breaks all my tests...

**Comment by MikeMitterer** [comment]
@ltackmann I've pushed a new version to the repo that solves the problem (#30 )
Could you please publish the new version asap because, as said, the current version breaks most of my internal tests

**Pull request merged**
